version: '3.9'

services:
  notifications_service:
    build:
      context: ./notifications_service
      dockerfile: Dockerfile
    container_name: notifications_service
    ports:
      - "8002:8002"
    environment:
      MONGO_URI: mongodb://mongodb:27017
      JWT_SECRET: b1218b936ff9bba74233a42c6e633ed432cf14ded1d43daf2c0f81280f5cda479696aa7449a77b0a4cf05253fea8e6d8ef886577ad7dfa05976f8f798a2f557a
      ALGORITHM: "HS256"
      USER_SERVICE_URL: "http://user_service:8000"
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_QUEUE: recommendation_queue
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
      REDIS_HOST: redis
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      mongodb:
        condition: service_started
      user_service:
        condition: service_started
    restart: always

  db:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: fastapi_user
      POSTGRES_PASSWORD: fastapi_pass
      POSTGRES_DB: users_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "fastapi_user", "-d", "users_db"]
      interval: 5s
      timeout: 3s
      retries: 10

  user_service:
    build:
      context: ./user_service
      dockerfile: Dockerfile
    container_name: user_service
    ports:
      - "8050:8000"
    volumes:
      - ./user_service/data:/app/data
    environment:
      DATABASE_URL: postgresql://fastapi_user:fastapi_pass@db/users_db
      SECRET_KEY: b1218b936ff9bba74233a42c6e633ed432cf14ded1d43daf2c0f81280f5cda479696aa7449a77b0a4cf05253fea8e6d8ef886577ad7dfa05976f8f798a2f557a
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 120
    depends_on:
      db:
        condition: service_healthy
    restart: always

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    restart: always

  recommendation_service:
    build:
      context: ./recommendation_service
      dockerfile: Dockerfile
    container_name: recommendation_service
    ports:
      - "8003:8003"
    environment:
      - MONGO_URI=mongodb://mongo_recommendation:27017/recommendations
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_QUEUE=recommendation_queue
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    depends_on:
      mongo_recommendation:
        condition: service_started
      rabbitmq:
        condition: service_healthy

  mongo_recommendation:
    image: mongo:6.0
    container_name: mongo_recommendation
    ports:
      - "27019:27017"
    volumes:
      - mongo_recommendation_data:/data/db

  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15692:15692"
    environment:
      RABBITMQ_ERLANG_COOKIE: secret
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    restart: always
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

  notifications_worker:
    build: ./notifications_service
    container_name: notifications_worker
    depends_on:
      redis:
        condition: service_healthy
      notifications_service:
        condition: service_started
    environment:
      - REDIS_HOST=redis
      - MONGO_URI=mongodb://mongodb:27017
    volumes:
      - ./notifications_service/src:/app/src
    command: ["node", "src/worker.js"]

  notifications_dlq_worker:
    build: ./notifications_service
    container_name: notifications_dlq_worker
    depends_on:
      redis:
        condition: service_healthy
      notifications_service:
        condition: service_started
      notifications_worker:
        condition: service_started
    environment:
      - REDIS_HOST=redis
      - MONGO_URI=mongodb://mongodb:27017
    volumes:
      - ./notifications_service/src:/app/src
    command: ["node", "src/dlqWorker.js"]

  graphql_gateway:
    build:
      context: ./graphql_gateway
      dockerfile: Dockerfile
    container_name: graphql_gateway
    ports:
      - "4000:4000"
    depends_on:
      user_service:
        condition: service_started
      notifications_service:
        condition: service_started
      recommendation_service:
        condition: service_started
      redis:
        condition: service_healthy
    env_file:
      - ./graphql_gateway/.env

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./monitoring/grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      prometheus:
        condition: service_started

  redis-exporter:
    image: oliver006/redis_exporter
    container_name: redis_exporter
    environment:
      - REDIS_ADDR=redis:6379
    ports:
      - "9121:9121"
    depends_on:
      redis:
        condition: service_healthy

volumes:
  mongodata:
  pgdata:
  mongo_recommendation_data:
  grafana-data:
