global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "redis"
    static_configs:
      - targets: ["redis-exporter:9121"]

  - job_name: "rabbitmq"
    static_configs:
      - targets: ["rabbitmq:15692"]

  - job_name: "notification_service"
    static_configs:
      - targets: ["notification_service:8002"]

  - job_name: "user_service"
    static_configs:
      - targets: ["user_service:8001"]

  - job_name: "recommendation_service"
    static_configs:
      - targets: ["recommendation_service:8003"]
