version: '3.8'

services:
  notification_service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    environment:
      - MONGO_URI=mongodb://mongo_notification:27017/notifications
      - JWT_SECRET=supersecretkey
    depends_on:
      - mongo_notification

  mongo_notification:
    image: mongo:latest
    container_name: mongo_notification
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
